name: testPr

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: neumantm/domain-connect-dyndns:test
